### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by larshp** [ThePlenkov/abapify#1]
I guess you have already seen
https://blogs.sap.com/2021/02/22/abap-openapi-client-generation-in-abap/
and
https://github.com/abap-openapi/abap-openapi
?

**Comment by ThePlenkov** [comment]
@larshp  Hi Lars. Haha - wow - cool that you've found my project.

Actually I was inspired by your project - and what I do - it's all to come to the same goal - to generate abapGit artifacts. However I have another idea of implementation - very soon I hope to be able to present first results =)

**Comment by larshp** [comment]
ok
